server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    discovery:
      enabled: true
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: wishlist
          uri: lb://wishlist
          predicates:
            - Path=/api/v1/wishlist/**
          filters:
            - AuthFilter

        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/api/v1/auth/**,/api/v1/user/**
logging:
  level:
    root: INFO